In [16]:
import numpy as np # インポート
A =np.array([   #A配列
    [0,1],
    [2,3],
    [4,5]])
B =np.array([   #B配列
    [0,1,2,3],
    [4,5,6,7]])
result = np.dot(A,B)    #行列積
print(result)
max_value = np.max(result)
print(max_value)
print(result[:, 1])   #二列めを表示



[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
[ 5 17 29]


# 新しいセクション